# Generated by Django 6.0.2 on 2026-04-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('photo', 'Вышивка по фото'), ('personal', 'Персональный дизайн вышивки'), ('restoration', 'Восстановление одежды'), ('consultation', 'Консультация'), ('other', 'Другое')], max_length=200, verbose_name='Тема заказа')),
                ('name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('tg_nick', models.CharField(max_length=200, verbose_name='Телеграмм')),
                ('descp_order', models.TextField(verbose_name='Описание заказа')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Имя клиента')),
            ],
        ),
    ]
